#! /bin/bash
cat Blender_2.90/fox_head.obj.?? > Blender_2.90/fox_head.obj
cat Blender_2.77/Cube_1439.obj.?? > Blender_2.77/Cube_1439.obj
cat Salle_De_Bain/salle_de_bain.obj.?? > Salle_De_Bain/salle_de_bain.obj
